### ISSUE TITLE
Usage block in README

### ISSUE THREAD

**Issue by emilos** [Conduitry/defiler#1]
I like fun projects like this one :). Would you mind adding a Usage block in readme or integration tests so it's more obvious how to use it?

**Comment by Conduitry** [comment]
Hi! Sorry about the big delay on this. I've been fiddling recently with this again to make it more powerful but also to make its API simpler. I just released a version I'm feeling pretty happy about - and it also has a new [guide section](https://github.com/Conduitry/defiler/blob/master/GUIDE.md) in the docs.
